version: 1.0.{build}
before_build:
- nuget restore mapresty-client-dotnet.sln
branches:
  only:
  - master
skip_tags: true
build:
  project: mapresty-client-dotnet.sln
  verbosity: minimal
artifacts:
  - path: '**\*.nupkg'
    type: NuGetPackage
deploy:
  provider: NuGet
  apk_key:
    secure: nFpgHCOjA2HLkJrnA3fohdBETPBdxDWftMSUVWAXUi53wVH3oJLGTEYTlJgcvjUf
  artifact: MapResty.Client.nupkg
