version: 1.0.{build}
before_build:
- nuget restore mapresty-client-dotnet.sln
branches:
  only:
  - master
skip_tags: true
build:
  project: mapresty-client-dotnet.sln
  publish_nuget: true 
  verbosity: minimal
artifacts:
  - path: MapResty.Client.nupkg
    type: Auto
deploy:
    # Deploying to NuGet feed
  - provider: NuGet
    apk_key:
      secure: nFpgHCOjA2HLkJrnA3fohdBETPBdxDWftMSUVWAXUi53wVH3oJLGTEYTlJgcvjUf
    artifact: MapResty.Client.nupkg
    # Deploy to GitHub Releases
  - provider: GitHub
    artifact: MapResty.Client.nupkg
    draft: false
    prerelease: false
    on:
      branch: master                # release from master branch only
      appveyor_repo_tag: true       # deploy on tag push only
