version: 1.0.{build}
before_build:
- nuget restore mapresty-client-dotnet.sln
branches:
  only:
  - master
# skip_tags: true
only_commits:
  message: /build/                # Start a new build if message contains 'build'
# enable patching of AssemblyInfo.* files
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"
# build Configuration, i.e. Debug, Release, etc.
configuration: Release
build:
  project: mapresty-client-dotnet.sln
  publish_nuget: true 
  verbosity: minimal
deploy:
    # Deploying to NuGet feed
  - provider: NuGet
    api_key:
      secure: nFpgHCOjA2HLkJrnA3fohdBETPBdxDWftMSUVWAXUi53wVH3oJLGTEYTlJgcvjUf
    artifact: /.*\.nupkg/
    # Deploy to GitHub Releases
  - provider: GitHub
    auth_token:
      secure: 7V+oW4wVzgKgsu21T5GQJg4i1gVpA/XyoYq0OoFJ8oXmDTxP3QTwqTno6W0yFbOU
    artifact: /.*\.nupkg/
    draft: false
    prerelease: false
    on:
      branch: master                # release from master branch only
      appveyor_repo_tag: true       # deploy on tag push only
